language: android
sudo: false
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
    - sys-img-armeabi-v7a-android-22
    
    licenses:
       - 'android-sdk-license-.+'
       


script:
  - android list target
  - ./gradlew connectedAndroidTest
